blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions and Answers about IntelliJ V
    url: https://github.com/i582/vlang-idea/discussions/categories/questions-and-answers
    about: You can ask and answer questions about plugin in the discussions forum.

  - name: 💬 V Discord Server
    url: https://discord.gg/vlang
    about: You can join our Discord server for real time discussion and support
